### ISSUE TITLE
Is "Requirement: SugarCRM 7.8" a typo?

### ISSUE THREAD

**Issue by AlanApter** [sugarcrm/uncon#19]
Currently the latest release of Sugar is 7.7.0. Is this a sneak preview or did you mean 7.7?

**Comment by mmarum-sugarcrm** [comment]
Some of what was presented was a preview of things coming soon.  There are a couple of examples here tagged for 7.7.1 or 7.8.0.

**Comment by AlanApter** [comment]
Thanks Matt!
